#!/bin/sh

# Run the Jest tests
echo "Running tests before pushing..."
npm run test
TEST_RESULT=$?

if [ $TEST_RESULT -ne 0 ]; then
  echo "Tests failed, aborting push."
  exit 1
fi

# Run the Next.js lint command
echo "Running lint before pushing..."
npm run lint
LINT_RESULT=$?

if [ $LINT_RESULT -ne 0 ]; then
  echo "Linting failed, aborting push."
  exit 1
fi

echo "All tests and linting passed, proceeding with push."
exit 0
